# Generated by Django 6.1 on 2026-09-14 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonetizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_requires_payment', models.BooleanField(default=False, help_text='Quando ligado, novos cadastros só são aceitos com um código de acesso válido (indicado após o pagamento).', verbose_name='cadastro exige pagamento')),
                ('price_label', models.CharField(default='R$ 9,90 / mês', help_text='Texto exibido na tela de cadastro quando o pagamento é exigido.', max_length=60, verbose_name='descrição do preço')),
                ('payment_instructions', models.TextField(blank=True, help_text='Como o visitante deve proceder para obter o código de acesso.', verbose_name='instruções de pagamento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuração de monetização',
                'verbose_name_plural': 'configuração de monetização',
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código que o visitante informa no cadastro após pagar.', max_length=40, unique=True, verbose_name='código')),
                ('note', models.CharField(blank=True, help_text='Ex.: canal de venda, cliente, lote.', max_length=120, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('revoked', models.BooleanField(default=False, verbose_name='revogado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usado por')),
            ],
            options={
                'verbose_name': 'código de acesso',
                'verbose_name_plural': 'códigos de acesso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=64, verbose_name='recurso')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='contagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'evento de feature',
                'verbose_name_plural': 'eventos de feature',
                'indexes': [models.Index(fields=['date'], name='painel_feat_date_idx'), models.Index(fields=['feature'], name='painel_feat_feature_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'feature', 'date'), name='painel_featureevent_user_feature_date_uniq')],
            },
        ),
    ]
