# Generated by Django 6.1 on 2026-09-14 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)')], default='percent', max_length=10, verbose_name='tipo')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor do desconto')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ilimitado.', verbose_name='limite de usos')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='usos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual'), ('lifetime', 'Vitalício')], default='monthly', max_length=10, verbose_name='ciclo')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Dias de acesso liberados. Use 0 para vitalício/ilimitado.', verbose_name='duração (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['order', 'price', 'name'],
            },
        ),
        migrations.AddField(
            model_name='monetizationconfig',
            name='support_contact',
            field=models.CharField(blank=True, help_text='WhatsApp/email exibido ao cliente para dúvidas de pagamento.', max_length=120, verbose_name='contato de suporte'),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plano liberado ao resgatar este código.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_codes', to='painel.plan', verbose_name='plano'),
        ),
        migrations.AddField(
            model_name='monetizationconfig',
            name='default_plan',
            field=models.ForeignKey(blank=True, help_text='Plano liberado por padrão quando a monetização está ativa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='painel.plan', verbose_name='plano padrão'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('trial', 'Período de teste'), ('expired', 'Expirada'), ('canceled', 'Cancelada')], default='active', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('notes', models.CharField(blank=True, max_length=160, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='painel.plan', verbose_name='plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartão'), ('boleto', 'Boleto'), ('transfer', 'Transferência'), ('other', 'Outro')], default='pix', max_length=10, verbose_name='método')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('refunded', 'Reembolsado'), ('canceled', 'Cancelado')], default='pending', max_length=10, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='painel.coupon', verbose_name='cupom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='painel.plan', verbose_name='plano')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='painel.subscription', verbose_name='assinatura')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='painel_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='painel_sub_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='painel_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='painel_pay_created_idx'),
        ),
    ]
