# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Conta usada por padrão em lançamentos rápidos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.account', verbose_name='conta padrão'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
