# Generated by Django 6.1 on 2026-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paying',
            field=models.BooleanField(default=False, help_text='Indica se o usuário pagou ou possui plano ativo.', verbose_name='pagante'),
        ),
    ]
