# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('institution', models.CharField(blank=True, max_length=120, verbose_name='instituição')),
                ('type', models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('cash', 'Carteira / dinheiro físico'), ('digital', 'Conta digital'), ('investment', 'Investimento'), ('other', 'Outros')], default='checking', max_length=20, verbose_name='tipo')),
                ('initial_balance', models.IntegerField(default=0, verbose_name='saldo inicial (centavos)')),
                ('initial_balance_date', models.DateField(blank=True, null=True, verbose_name='data do saldo inicial')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('archived', 'Arquivada'), ('closed', 'Encerrada')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('transfer', 'Transferência')], default='expense', max_length=20, verbose_name='tipo')),
                ('is_default', models.BooleanField(default=False, verbose_name='categoria padrão')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.category', verbose_name='categoria pai')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita')], max_length=20, verbose_name='tipo')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('amount', models.IntegerField(verbose_name='valor (centavos)')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='monthly', max_length=20, verbose_name='frequência')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='a cada (períodos)')),
                ('start_date', models.DateField(verbose_name='data inicial')),
                ('end_date', models.DateField(blank=True, help_text='Opcional; vazio = indefinida.', null=True, verbose_name='data final')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='1 a 31 (usado em mensal).', null=True, verbose_name='dia do mês')),
                ('weekday', models.PositiveIntegerField(blank=True, help_text='0=segunda ... 6=domingo.', null=True, verbose_name='dia da semana')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('ended', 'Encerrada')], default='active', max_length=20, verbose_name='status')),
                ('next_run_date', models.DateField(blank=True, null=True, verbose_name='próxima ocorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='finance.account', verbose_name='conta')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='cards.creditcard', verbose_name='cartão')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='finance.category', verbose_name='categoria')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'recorrência',
                'verbose_name_plural': 'recorrências',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('transfer', 'Transferência'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='tipo')),
                ('amount', models.IntegerField(verbose_name='valor (centavos)')),
                ('date', models.DateField(verbose_name='data')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('external_id', models.CharField(blank=True, default='', help_text='Identificador de origem para importação/conciliação futura.', max_length=128, verbose_name='identificador externo')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('imported_csv', 'Importado (CSV)'), ('imported_ofx', 'Importado (OFX)'), ('recurrence', 'Recorrência'), ('system', 'Sistema')], default='manual', max_length=20, verbose_name='origem')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='conciliada')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='conciliada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account', verbose_name='conta')),
                ('card_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.installmentpurchase', verbose_name='compra no cartão')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category', verbose_name='categoria')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('recurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.recurringrule', verbose_name='recorrência')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='valor (centavos)')),
                ('date', models.DateField(verbose_name='data')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account', verbose_name='conta de origem')),
                ('in_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in', to='finance.transaction', verbose_name='perna de entrada')),
                ('out_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out', to='finance.transaction', verbose_name='perna de saída')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account', verbose_name='conta de destino')),
            ],
            options={
                'verbose_name': 'transferência',
                'verbose_name_plural': 'transferências',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.transfer', verbose_name='transferência'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('initial_balance__gte', 0)), name='finance_account_initial_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'parent', 'kind'), name='finance_category_unique_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_recurring_rule_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1)), name='finance_recurring_rule_interval_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_transfer_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='finance_transfer_from_ne_to'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'date'], name='finance_tra_owner_i_466876_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'account', 'date'], name='finance_tra_owner_i_4d3ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_id'], name='finance_tra_externa_5e4f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_transaction_amount_gt_0'),
        ),
    ]
