# Generated by Django 6.1 on 2026-09-03 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='normalized_description',
            field=models.CharField(blank=True, default='', help_text='Derivada da descrição original; nunca substitui a original.', max_length=200, verbose_name='descrição normalizada'),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('source', models.CharField(choices=[('catalog', 'Catálogo'), ('user', 'Usuário'), ('auto', 'Automática')], default='catalog', max_length=20, verbose_name='origem')),
                ('default_category_name', models.CharField(blank=True, default='', max_length=120, verbose_name='categoria padrão sugerida')),
                ('is_default', models.BooleanField(default=False, verbose_name='estabelecimento padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL, verbose_name='proprietário (null = global)')),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.merchant', verbose_name='estabelecimento'),
        ),
        migrations.CreateModel(
            name='MerchantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, verbose_name='alias')),
                ('source', models.CharField(choices=[('catalog', 'Catálogo'), ('user', 'Usuário'), ('history', 'Histórico do usuário'), ('auto', 'Automática')], default='catalog', max_length=20, verbose_name='origem')),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='confiança')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='usos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='finance.merchant', verbose_name='estabelecimento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_aliases', to=settings.AUTH_USER_MODEL, verbose_name='proprietário (null = global)')),
            ],
            options={
                'verbose_name': 'alias de estabelecimento',
                'verbose_name_plural': 'aliases de estabelecimento',
                'ordering': ['alias'],
            },
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='finance_merchant_unique_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='merchantalias',
            constraint=models.UniqueConstraint(fields=('owner', 'alias'), name='finance_merchantalias_unique_per_owner'),
        ),
    ]
