# Generated by Django 6.1 on 2026-09-03 14:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_normalized_description_merchant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('condition_type', models.CharField(choices=[('contains', 'Descrição contém'), ('merchant', 'Merchant')], default='contains', max_length=20, verbose_name='tipo de condição')),
                ('pattern', models.CharField(blank=True, default='', max_length=200, verbose_name='padrão')),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('any', 'Qualquer')], default='any', max_length=10, verbose_name='tipo de movimentação')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('source', models.CharField(default='user', max_length=20, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='finance.category', verbose_name='categoria (ação)')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='finance.merchant', verbose_name='estabelecimento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to=settings.AUTH_USER_MODEL, verbose_name='proprietário (null = global)')),
            ],
            options={
                'verbose_name': 'regra de classificação',
                'verbose_name_plural': 'regras de classificação',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=120, verbose_name='nome da categoria')),
                ('subcategory_name', models.CharField(blank=True, default='', max_length=120, verbose_name='nome da subcategoria')),
                ('normalized_description', models.CharField(blank=True, default='', max_length=200, verbose_name='descrição normalizada')),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4, verbose_name='confiança')),
                ('classification_source', models.CharField(choices=[('user_correction', 'Correção do usuário'), ('user_rule', 'Regra do usuário'), ('merchant', 'Merchant conhecido'), ('alias', 'Alias conhecido'), ('history', 'Histórico do usuário'), ('global_rule', 'Regra global'), ('context', 'Contexto'), ('manual', 'Manual'), ('movement', 'Movimentação (não consumo)'), ('none', 'Sem evidência')], default='none', max_length=30, verbose_name='origem da decisão')),
                ('mcc', models.CharField(blank=True, default='', max_length=8, verbose_name='código do comércio')),
                ('needs_review', models.BooleanField(default=False, verbose_name='precisa de revisão')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisto em')),
                ('user_corrected', models.BooleanField(default=False, verbose_name='corrigida pelo usuário')),
                ('is_movement', models.BooleanField(default=False, verbose_name='movimentação (não consumo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='finance.category', verbose_name='categoria (FK)')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='finance.merchant', verbose_name='estabelecimento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='finance.classificationrule', verbose_name='regra aplicada')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='finance.transaction', verbose_name='transação')),
            ],
            options={
                'verbose_name': 'análise de transação',
                'verbose_name_plural': 'análises de transação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='chave')),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('transfer', 'Transferência')], default='expense', max_length=10, verbose_name='tipo')),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0.90'), max_digits=4, verbose_name='confiança')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='confirmações')),
                ('last_corrected_at', models.DateTimeField(auto_now=True, verbose_name='última correção')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='finance.category', verbose_name='categoria (escolhida)')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferences', to='finance.merchant', verbose_name='estabelecimento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'preferência do usuário',
                'verbose_name_plural': 'preferências do usuário',
                'ordering': ['-count', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['owner', 'is_active', 'priority'], name='finance_cla_owner_i_8638c7_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionanalysis',
            index=models.Index(fields=['owner', 'classification_source'], name='finance_tra_owner_i_917585_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionanalysis',
            index=models.Index(fields=['needs_review'], name='finance_tra_needs_r_dfb5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['owner', 'key'], name='finance_use_owner_i_35c42b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.UniqueConstraint(fields=('owner', 'key'), name='finance_userpreference_unique_owner_key'),
        ),
    ]
