# Generated by Django 6.1 on 2026-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_classificationrule_transactionanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrule',
            name='category_name',
            field=models.CharField(blank=True, default='', help_text='Nome (raiz/subcategoria) da taxonomia a classificar; resolvido para a categoria real do usuário em tempo de execução.', max_length=120, verbose_name='nome da categoria (ação)'),
        ),
    ]
