# Generated by Django 6.1 on 2026-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_classificationrule_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionanalysis',
            name='classification_source',
            field=models.CharField(choices=[('user_correction', 'Correção do usuário'), ('user_rule', 'Regra do usuário'), ('merchant', 'Merchant conhecido'), ('alias', 'Alias conhecido'), ('history', 'Histórico do usuário'), ('global_rule', 'Regra global'), ('context', 'Contexto'), ('manual', 'Manual'), ('movement', 'Movimentação (não consumo)'), ('semantic', 'Classificador semântico (opcional)'), ('none', 'Sem evidência')], default='none', max_length=30, verbose_name='origem da decisão'),
        ),
    ]
