# Generated by Django 6.1 on 2026-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_transactionanalysis_classification_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('cash', 'Carteira / dinheiro físico'), ('digital', 'Conta digital'), ('investment', 'Investimento'), ('credit_card', 'Cartão de crédito'), ('other', 'Outros')], default='checking', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='transactionanalysis',
            name='classification_source',
            field=models.CharField(choices=[('user_correction', 'Correção do usuário'), ('user_rule', 'Regra do usuário'), ('merchant', 'Merchant conhecido'), ('alias', 'Alias conhecido'), ('history', 'Histórico do usuário'), ('global_rule', 'Regra global'), ('context', 'Contexto'), ('manual', 'Manual'), ('movement', 'Movimentação (não consumo)'), ('nature', 'Natureza da transação (agnóstica de banco)'), ('suggested', 'Categoria sugerida pelo cliente/arquivo'), ('semantic', 'Classificador semântico (opcional)'), ('none', 'Sem evidência')], default='none', max_length=30, verbose_name='origem da decisão'),
        ),
    ]
