# Generated by Django 6.1 on 2026-09-07 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_creditcard_cards_credi_owner_i_40faa4_idx_and_more'),
        ('finance', '0007_add_credit_card_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'type', 'date'], name='finance_tra_owner_i_c77419_idx'),
        ),
    ]
