# Generated by Django 6.1 on 2026-09-02 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(verbose_name='data')),
                ('assets', models.IntegerField(default=0, verbose_name='ativos (centavos)')),
                ('liabilities', models.IntegerField(default=0, verbose_name='passivos (centavos)')),
                ('net_worth', models.IntegerField(default=0, verbose_name='patrimônio líquido (centavos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'ponto de patrimônio',
                'verbose_name_plural': 'pontos de patrimônio',
                'ordering': ['-recorded_on'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'recorded_on'), name='networth_snapshot_per_day')],
            },
        ),
    ]
