# Generated by Django 6.1 on 2026-09-02 15:03

import apps.comprovantes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=60, verbose_name='código')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('kind', models.CharField(choices=[('receipt', 'Comprovante / Recibo'), ('invoice', 'Nota fiscal'), ('warranty', 'Garantia'), ('health', 'Recibo de saúde (IR)'), ('other', 'Outros')], default='receipt', max_length=20, verbose_name='tipo')),
                ('file', models.FileField(upload_to=apps.comprovantes.models.comprovante_upload_to, verbose_name='arquivo')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='expiração da garantia')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'comprovante',
                'verbose_name_plural': 'comprovantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
