# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('closing_date', models.DateField(verbose_name='data de fechamento')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('paid', 'Paga'), ('overdue', 'Atrasada')], default='open', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'fatura de cartão',
                'verbose_name_plural': 'faturas de cartão',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='parcela nº')),
                ('amount', models.IntegerField(verbose_name='valor (centavos)')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('overdue', 'Atrasada'), ('skipped', 'Pulada')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'parcela',
                'verbose_name_plural': 'parcelas',
                'ordering': ['purchase', 'number'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('total_amount', models.IntegerField(verbose_name='valor total (centavos)')),
                ('installment_count', models.PositiveIntegerField(verbose_name='quantidade de parcelas')),
                ('installment_amount', models.IntegerField(verbose_name='valor da parcela (centavos)')),
                ('first_due_date', models.DateField(verbose_name='primeira parcela')),
                ('status', models.CharField(choices=[('ongoing', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='ongoing', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'compra parcelada',
                'verbose_name_plural': 'compras parceladas',
                'ordering': ['-first_due_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('institution', models.CharField(blank=True, max_length=120, verbose_name='instituição')),
                ('limit', models.IntegerField(default=0, verbose_name='limite (centavos)')),
                ('closing_day', models.PositiveIntegerField(default=1, verbose_name='dia de fechamento')),
                ('due_day', models.PositiveIntegerField(default=10, verbose_name='dia de vencimento')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('blocked', 'Bloqueado'), ('closed', 'Encerrado')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'cartão de crédito',
                'verbose_name_plural': 'cartões de crédito',
                'ordering': ['name'],
            },
        ),
    ]
