# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='finance.account', verbose_name='conta de pagamento'),
        ),
        migrations.AddField(
            model_name='creditcardinvoice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='cards.creditcard', verbose_name='cartão'),
        ),
        migrations.AddField(
            model_name='creditcardinvoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário'),
        ),
        migrations.AddField(
            model_name='creditcardinvoice',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='finance.account', verbose_name='conta de pagamento'),
        ),
        migrations.AddField(
            model_name='creditcardinvoice',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoices', to='finance.transaction', verbose_name='pagamento'),
        ),
        migrations.AddField(
            model_name='installment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='cards.creditcardinvoice', verbose_name='fatura'),
        ),
        migrations.AddField(
            model_name='installment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário'),
        ),
        migrations.AddField(
            model_name='installmentpurchase',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='cards.creditcard', verbose_name='cartão'),
        ),
        migrations.AddField(
            model_name='installmentpurchase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário'),
        ),
        migrations.AddField(
            model_name='installment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='cards.installmentpurchase', verbose_name='compra'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('limit__gte', 0)), name='cards_creditcard_limit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('closing_day__gte', 1), ('closing_day__lte', 31)), name='cards_creditcard_closing_day_range'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__gte', 1), ('due_day__lte', 31)), name='cards_creditcard_due_day_range'),
        ),
        migrations.AddConstraint(
            model_name='creditcardinvoice',
            constraint=models.UniqueConstraint(fields=('card', 'period_start', 'period_end'), name='cards_invoice_unique_per_period'),
        ),
        migrations.AddConstraint(
            model_name='installmentpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='cards_purchase_total_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='installmentpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 1)), name='cards_purchase_count_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='installmentpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('installment_amount__gt', 0)), name='cards_purchase_installment_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cards_installment_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='cards_installment_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('purchase', 'number'), name='cards_installment_unique_per_purchase'),
        ),
    ]
