# Generated by Django 6.1 on 2026-09-07 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
        ('finance', '0007_add_credit_card_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['owner', 'status'], name='cards_credi_owner_i_40faa4_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardinvoice',
            index=models.Index(fields=['owner', 'status', 'due_date'], name='cards_credi_owner_i_d46020_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['purchase', 'status'], name='cards_insta_purchas_83681f_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['invoice'], name='cards_insta_invoice_9926b3_idx'),
        ),
    ]
