# Generated by Django 6.1 on 2026-08-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('category', 'Por categoria'), ('global', 'Global')], max_length=20, verbose_name='tipo')),
                ('period', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='monthly', max_length=20, verbose_name='período')),
                ('limit_amount', models.IntegerField(default=0, verbose_name='limite (centavos)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data inicial')),
                ('end_date', models.DateField(blank=True, help_text='Opcional; vazio = ativo.', null=True, verbose_name='data final')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['kind', 'id'],
            },
        ),
    ]
