# Generated by Django 6.1 on 2026-09-07 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('finance', '0007_add_credit_card_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['owner', 'is_active'], name='budgets_bud_owner_i_66b710_idx'),
        ),
    ]
