# Generated by Django 6.1 on 2026-09-02 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, default='', help_text='Uma frase de conclusão curta, para exibir na dashboard.', max_length=200, verbose_name='resumo')),
                ('content', models.TextField(blank=True, default='', verbose_name='conteúdo')),
                ('via_ai', models.BooleanField(default=True, verbose_name='gerado por IA')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='gerado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'relatório de análise',
                'verbose_name_plural': 'relatórios de análise',
                'ordering': ['-generated_at'],
            },
        ),
    ]
