# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('loan', 'Empréstimo'), ('financing', 'Financiamento'), ('external_installment', 'Parcelamento externo'), ('other', 'Outros')], default='loan', max_length=30, verbose_name='tipo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('total_amount', models.IntegerField(default=0, verbose_name='valor total (centavos)')),
                ('paid_amount', models.IntegerField(default=0, verbose_name='valor pago (centavos)')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='taxa de juros (% a.m.)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data inicial')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('creditor', models.CharField(blank=True, max_length=120, verbose_name='credor')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paid_off', 'Quitada'), ('defaulted', 'Inadimplente'), ('archived', 'Arquivada')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'dívida',
                'verbose_name_plural': 'dívidas',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='debts_debt_total_gte_0'), models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='debts_debt_paid_gte_0'), models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('total_amount'))), name='debts_debt_paid_le_total')],
            },
        ),
    ]
