# Generated by Django 6.1 on 2026-09-07 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['owner', 'status'], name='debts_debt_owner_i_a604b4_idx'),
        ),
    ]
