# Generated by Django 6.1 on 2026-09-03 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=24, unique=True, verbose_name='identificador do lote')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('xlsx', 'XLSX')], max_length=10, verbose_name='tipo de arquivo')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='nome do arquivo')),
                ('original_file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='arquivo original')),
                ('detected_count', models.PositiveIntegerField(default=0, verbose_name='detectadas')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='importadas')),
                ('ignored_count', models.PositiveIntegerField(default=0, verbose_name='ignoradas')),
                ('pending_count', models.PositiveIntegerField(default=0, verbose_name='pendentes')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='com erro')),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('ready', 'Pronto para revisão'), ('committed', 'Confirmado'), ('discarded', 'Descartado'), ('failed', 'Falhou')], default='processing', max_length=20, verbose_name='status')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name='detalhe do erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('committed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'Lote de importação',
                'verbose_name_plural': 'Lotes de importação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, default='', max_length=128, verbose_name='id de origem')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='id externo')),
                ('date', models.DateField(verbose_name='data')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='descrição')),
                ('original_description', models.CharField(blank=True, default='', max_length=200, verbose_name='descrição original')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='valor (centavos)')),
                ('direction', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='direção')),
                ('confidence', models.CharField(choices=[('high', 'Alta confiança'), ('review', 'Precisa de revisão'), ('duplicate', 'Possível duplicada')], default='high', max_length=10, verbose_name='confiança')),
                ('row_status', models.CharField(choices=[('ready', 'Pronta'), ('review', 'Em revisão'), ('ignored', 'Ignorada'), ('imported', 'Importada'), ('error', 'Erro')], default='ready', max_length=10, verbose_name='status da linha')),
                ('skip_reason', models.CharField(blank=True, default='', max_length=120, verbose_name='motivo de descarte')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows', to='imports.importbatch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_transactions', to='finance.category')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_transactions_default', to='finance.account')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_candidates', to='imports.stagedtransaction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'Movimentação em revisão',
                'verbose_name_plural': 'Movimentações em revisão',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status', 'created_at'], name='imports_imp_status_f70ade_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedtransaction',
            index=models.Index(fields=['batch', 'row_status'], name='imports_sta_batch_i_d39585_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedtransaction',
            index=models.Index(fields=['owner', 'external_id'], name='imports_sta_owner_i_c5a711_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='imports_staged_amount_gt_0'),
        ),
    ]
