# Generated by Django 6.1 on 2026-09-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_normalized_description_merchant_and_more'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_transactions', to='finance.merchant'),
        ),
        migrations.AddField(
            model_name='stagedtransaction',
            name='normalized_description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='descrição normalizada'),
        ),
    ]
