# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('target_amount', models.IntegerField(default=0, verbose_name='valor objetivo (centavos)')),
                ('current_amount', models.IntegerField(default=0, verbose_name='valor atual (centavos)')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='data objetivo')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('achieved', 'Alcançada'), ('archived', 'Arquivada')], default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gte', 0)), name='goals_goal_target_gte_0'), models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='goals_goal_current_gte_0')],
            },
        ),
    ]
